about/urls.py
from django.urls import path
from .views import index

app_name = 'about'

urlpatterns = [
    path('', index, name='index')
]

crowdfunding/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('homepage.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('social_django.urls', namespace='social')),
    path('donor/', include('googleLogin.urls')),
    path('registration/', include('RegistrationForm_Page.urls')),
    path('donations/', include('donation_page.urls')),
    path('donationform_page/', include('New_Donation_Form.urls')),
    path('profile/', include('user_profile.urls')),
    path('about', include('about.urls')),
]

homepage/urls.py
from django.urls import path
from .views import index

app_name = 'homepage'

urlpatterns = [
    path('', index, name='index')
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render
from data.models import Event

def index(req):

    programs = Event.objects.all()
    filter = req.GET.get('filter')
    if (filter == 'viewed'):
        programs = Event.objects.all().order_by('-viewed')
    elif (filter == 'recentdue'):
        programs = Event.objects.all().order_by('-due')

    return render(req, 'home.html', {'programs': programs})

homepage/templates/home.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block content %}
<section class="container">
  <div id="photoCarousel" class="carousel slide my-2" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#photoCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#photoCarousel" data-slide-to="1"></li>
      <li data-target="#photoCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-block w-100" src="{% static 'img/picture1.jpg' %}" alt="First slide">
        <div class="carousel-caption d-none d-md-block">
          <h5>Item 1</h5>
        </div>
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="{% static 'img/picture2.jpg' %}" alt="Second slide">
        <div class="carousel-caption d-none d-md-block">
          <h5>Item 2</h5>
        </div>
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="{% static 'img/picture3.jpg' %}" alt="Third slide">
        <div class="carousel-caption d-none d-md-block">
          <h5>Item 3</h5>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#photoCarousel" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#photoCarousel" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</section>

<section id="donation-programs">
  <div class="d-flex flex-row justify-content-between mt-5 mb-2">
    <h2>Donation Programs</h2>
    <div class="dropdown">
      <button class="btn btn-primary dropdown-toggle" type="button" id="filterDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Sort</button>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="filterDropdown">
        <a href="{% url 'homepage:index' %}?filter=recentdue#donation-programs" class="dropdown-item" type="button">By Most Recent Due Date</a>
        <a href="{% url 'homepage:index' %}?filter=viewed#donation-programs" class="dropdown-item" type="button">By Most Viewed</a>
      </div>
    </div>
  </div>

  {% for program in programs %}

  <div class="program row my-5">
    <div class="col-xs-12 col-md-3">
      <img src={{program.image_src}} alt="Program Photo" class="mx-auto">
    </div>
    <div class="col-xs-12 col-md-9 d-flex align-items-center my-2">
      <div>
        <h3>{{ program.title }}</h3>
        <p>{{ program.short_desc }}</p>
        <a href="donations/{{ program.id }}" class="btn btn-primary">See More</a>
      </div>
    </div>
  </div>

  {% endfor %}



</section>
{% endblock %}